# config.yaml

# --- API Configuration ---
# It's STRONGLY recommended to set GOOGLE_API_KEY as an environment variable in a .env file.
# This value is only used as a fallback if the environment variable is not set.
# google_api_key: "YOUR_GOOGLE_API_KEY_IF_NOT_USING_ENV_VAR"

# --- Rate Limiting (calls per period) ---
# Example: 5 calls per 60 seconds (1 minute) - Check your Google API quotas
rate_limit_calls: 5
rate_limit_period: 60

# --- LLM Configuration ---
# See https://ai.google.dev/models/gemini for available models
# llm_model_name: "models/gemini-2.0-flash" # Use for test runs
llm_model_name: "gemini-2.5-pro-exp-03-25" # Use for actual runs

# --- Output Configuration ---
output_folder: "analysis_results" # Folder where .md results will be saved
max_workers: 4 # Maximum number of parallel threads for processing sets

# --- Prompt File Paths ---
# Define specific prompts for each video type and comparison
early_take_prompt_file: "prompts/lol_early_take_prompt.txt"
retrospective_prompt_file: "prompts/lol_retrospective_prompt.txt"
compare_prompt_file: "prompts/lol_compare_takeaways_prompt.txt"

# --- YouTube Video Sets to Process ---
video_sets:
  - subject: "Aetherdrift"
    early_take:
      url: "https://www.youtube.com/watch?v=t9IsVW7tVxk"
    retrospective:
      url: "https://www.youtube.com/watch?v=bsxvnoUBCnU"

  - subject: "Duskmourne"
    early_take:
      url: "https://www.youtube.com/watch?v=xIXJT44obzc"
    retrospective:
      url: "https://www.youtube.com/watch?v=KttuUmEaBAc"

  - subject: "Bloomburrow"
    early_take:
      url: "https://www.youtube.com/watch?v=4AyJyfUh5q0"
    retrospective:
      url: "https://www.youtube.com/watch?v=MEUlVv3Cr5U"

  - subject: "Modern Horizons 3"
    early_take:
      url: "https://www.youtube.com/watch?v=0Af5xhA0uWs"
    retrospective:
      url: "https://www.youtube.com/watch?v=gK5Yy3-qQMs"

  - subject: "Outlaws of Thunder Junction"
    early_take:
      url: "https://www.youtube.com/watch?v=g8SUweU9oPc"
    retrospective:
      url: "https://www.youtube.com/watch?v=AEGKjMHhIeg"

  - subject: "Murders at Karlov Manor"
    early_take:
      url: "https://www.youtube.com/watch?v=jhsGXPOTbBU"
    retrospective:
      url: "https://www.youtube.com/watch?v=mFajL8fdfhQ"

  # - subject: "Another Example Set"
  #   early_take:
  #     url: "URL_FOR_OTHER_EARLY_VIDEO"
  #   retrospective:
  #     url: "URL_FOR_OTHER_RETRO_VIDEO"

  # Add more sets as needed following the structure above